// scripts/content-templates/index.js
//
// Canonical registry of ChatRealty content templates. Future requests
// like "create a simple-luxury carousel for listing X" resolve through
// this file. Adding a new template:
//   1. Add an entry below with the same shape
//   2. Document it in docs/content-templates/README.md
//   3. Save a memory note so future Claude sessions discover it
//
// Storage convention (Cloudinary, no local disk required):
//   jpsrealtor/content/<slug>/source/      — listing photos (PullPhotos → here)
//   jpsrealtor/content/<slug>/generated/   — pipeline outputs (slides, clips, audio)
//   jpsrealtor/content/<slug>/meta/        — captions, manifests, configs as raw uploads

const TEMPLATES = {
  "simple-luxury-carousel": {
    name: "Simple Luxury Carousel",
    type: "carousel",
    description:
      "10-slide editorial Instagram carousel for a single luxury listing. " +
      "Cover with left accent panel (configurable color) + Joseph headshot, " +
      "4 staged interior/exterior shots (Gemini composites Joseph into each room " +
      "with a banner label), CMA infographic with subdivision/city sales context, " +
      "3 cream-background text posts (story, qualities, pricing context), " +
      "and an eXp-branded CTA card with Joseph identity. 4:5 portrait 1080x1350.",
    requires: ["listingKey"],
    optional: ["color", "hook", "bodyCopy", "ctaCopy"],
    dataConfig: {
      path: "scripts/data/carousels/<slug>.js",
      shape: {
        slug: "string — kebab-case, usually number-streetname",
        color: "hex string without # — banner color for cover/CMA/CTA",
        handle: "string — IG handle, currently @instadella",
        cover: "{ hook, city, price, addressLine1, addressLine2, listingCredit, specs, body, agentName, headshotPublicId, sourcePhoto }",
        staged: "[{ n, photo, room, pose, expression, label, caption }] — 4 entries (slides 2-5)",
        cma: "{ scope, period, stats[4], listingLabel, listingPrice, pitch, color }",
        textPosts: "[{ n, paragraphs[], italicLast }] — 3 entries (slides 7-9)",
        cta: "{ label, agentName, agentLicense, paragraphs, italicLast, handle, headshotPublicId, brokerLogoPublicId, color }",
      },
    },
    invocation: {
      build: "node scripts/carousel-build.js <slug>",
      rebuildBookends: "node scripts/carousel-rebuild-bookends.js <slug>",
      rebuildStatic: "node scripts/carousel-rebuild-static.js <slug>",
      publish: "node scripts/carousel-upload-and-publish.js <slug>",
    },
    outputs: {
      slides: "10 JPGs at jpsrealtor/content/<slug>/generated/slides/slide-NN.jpg",
      caption: "jpsrealtor/content/<slug>/meta/caption.txt",
    },
    referenceListings: ["48750-el-nido", "77655-iroquois", "78890-lima", "81193-columbus"],
    estimatedCost: "~$0.05 in Gemini staging calls; Cloudinary egress",
    estimatedTime: "~45 seconds end-to-end",
    status: "production",
  },

  "staging-timelapse-reel": {
    name: "Staging Timelapse Reel",
    type: "reel",
    description:
      "~45-second 9:16 Instagram Reel showing a luxury listing's rooms being " +
      "staged from empty to fully furnished, intercut with smooth forward-dolly " +
      "transitions. Empty-room frames generated by Gemini (NanoBanana) from " +
      "the listing's actual staged photos; timelapse morphs by a video model " +
      "(currently Kling pro, target ComfyUI WAN 2.2 + Lightning LoRA on " +
      "RunPod Serverless). Narration via ElevenLabs (~85 words, ~40s), " +
      "stitched with ffmpeg over the video timeline with fade-to-black.",
    requires: ["listingKey"],
    optional: ["voiceId", "narrationScript", "rooms"],
    dataConfig: {
      path: "scripts/data/reels/<slug>.js",
      shape: {
        slug: "string",
        listingKey: "string",
        address: "string",
        shots: "[{ id, type, photo, duration, lumaPrompt, roomDesc? }] — typical 9 shots",
        narrationFile: "narration.mp3",
        narrationDurationSec: "number — measured by ffprobe",
        totalDurationSec: "number — target reel length (45s)",
      },
      narrationScript: "scripts/data/narration/<slug>.txt — plain text fed to ElevenLabs",
    },
    invocation: {
      generateNarration: "node scripts/generate-narration.js <slug> [voice_id]",
      prepEmpties: "node scripts/reel-prep-empties.js <slug>",
      kickoffKling: "node scripts/reel-kickoff-kling.js <slug>",
      kickoffLuma: "node scripts/reel-kickoff-luma.js <slug>",
      kickoffComfy: "(forthcoming) node scripts/reel-kickoff-comfyui.js <slug>",
    },
    outputs: {
      empties: "4 PNGs at jpsrealtor/content/<slug>/generated/empties/<shot-id>.png",
      narration: "jpsrealtor/content/<slug>/generated/narration.mp3",
      clips: "9 MP4s at jpsrealtor/content/<slug>/generated/clips/<shot-id>.mp4",
      finalReel: "jpsrealtor/content/<slug>/generated/reel-final.mp4",
    },
    referenceListings: ["1-makena"],
    estimatedCost:
      "Kling pro+std: ~$2.50/reel  ·  RunPod B200 self-hosted: ~$1.50/reel  ·  RunPod H100 self-hosted: ~$0.45/reel  ·  RunPod 4090 Serverless: ~$0.25/reel",
    estimatedTime: "~10 minutes end-to-end (audio + empties + 9 video gens + stitch)",
    status: "wip-phase-2-video-provider-selection",
  },
};

function getTemplate(id) {
  return TEMPLATES[id] || null;
}

function listTemplates() {
  return Object.keys(TEMPLATES).map((id) => ({
    id,
    name: TEMPLATES[id].name,
    type: TEMPLATES[id].type,
    status: TEMPLATES[id].status,
  }));
}

module.exports = { TEMPLATES, getTemplate, listTemplates };
