export type School = {
  id: string;
  slug: string;
  name: string;
  gradeLevel: "Elementary" | "Middle" | "High School";
  coordinates: { lat: number; lng: number };
  photoUrl: string;
  logoUrl: string;
  teamName: string;
  bio: string;
  phoneNumber: string;
  address: string;
  websiteUrl: string;
};

export type SchoolDistrict = {
  name: string;
  schools: {
    Elementary: School[];
    Middle: School[];
    HighSchool: School[];
  };
};

const desertSandsUnifiedSchoolDistrict: SchoolDistrict = {
  name: "Desert Sands Unified School District",
  schools: {
    Elementary: [
      {
        id: "1",
        slug: "carrillo-ranch-elementary",
        name: "Carrillo Ranch Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.7285, lng: -116.231 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Roadrunners",
        bio: "Carrillo Ranch Elementary School, established in 2003, serves students in grades K-5 with a commitment to academic excellence and a supportive learning environment.",
        phoneNumber: "(760) 238-9700",
        address: "43-775 Madison Street, Indio, CA 92201",
        websiteUrl: "https://cre.dsusd.us/",
      },
      {
        id: "2",
        slug: "james-e-carter-elementary",
        name: "James E. Carter Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.7225, lng: -116.3753 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Coyotes",
        bio: "James E. Carter Elementary School, opened in 1996, offers a comprehensive educational program for students in grades K-5, focusing on developing lifelong learners.",
        phoneNumber: "(760) 862-4370",
        address: "74-251 Hovley Lane East, Palm Desert, CA 92260",
        websiteUrl: "https://carter.dsusd.us/",
      },
      {
        id: "3",
        slug: "dr-reynaldo-j-carreon-jr-academy",
        name: "Dr. Reynaldo J. Carreon Jr. Academy",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.7282, lng: -116.2168 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Tigers",
        bio: "Dr. Reynaldo J. Carreon Jr. Academy, established in 2004, provides a nurturing environment for K-5 students, emphasizing academic achievement and personal growth.",
        phoneNumber: "(760) 775-3800",
        address: "47-368 Monroe Street, Indio, CA 92201",
        websiteUrl: "https://carreon.dsusd.us/",
      },
      {
        id: "4",
        slug: "amelia-earhart-elementary",
        name: "Amelia Earhart Elementary School of International Studies",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.748, lng: -116.27 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Eagles",
        bio: "Amelia Earhart Elementary, an IB World School since 2001, offers a rigorous international education program aimed at developing inquiring, knowledgeable, and caring young learners.",
        phoneNumber: "(760) 200-3720",
        address: "45-250 Dune Palms Road, Indio, CA 92201",
        websiteUrl: "https://earhart.dsusd.us/",
      },
      {
        id: "5",
        slug: "gerald-ford-elementary",
        name: "Gerald Ford Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.718, lng: -116.336 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Falcons",
        bio: "Gerald Ford Elementary School, opened in 1991, serves the Indian Wells community, providing quality education to students in grades K-5 with a focus on academic and social development.",
        phoneNumber: "(760) 772-4120",
        address: "44-210 Warner Trail, Indian Wells, CA 92210",
        websiteUrl: "https://ford.dsusd.us/",
      },
      {
        id: "6",
        slug: "benjamin-franklin-elementary",
        name: "Benjamin Franklin Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.6784, lng: -116.2968 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Patriots",
        bio: "Benjamin Franklin Elementary, an IB World School since 1997, offers a challenging educational program aimed at developing internationally minded students in grades K-5.",
        phoneNumber: "(760) 238-9424",
        address: "77-800 Calle Tampico, La Quinta, CA 92253",
        websiteUrl: "https://franklin.dsusd.us/",
      },
      {
        id: "7",
        slug: "herbert-hoover-elementary",
        name: "Herbert Hoover Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.7206, lng: -116.216 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Hawks",
        bio: "Herbert Hoover Elementary, established in 1951, is dedicated to providing a supportive and engaging learning environment for students in grades K-5.",
        phoneNumber: "(760) 775-3820",
        address: "44-300 Monroe Street, Indio, CA 92201",
        websiteUrl: "https://hoover.dsusd.us/",
      },
    ],
    Middle: [
      {
        id: "8",
        slug: "desert-ridge-academy",
        name: "Desert Ridge Academy",
        gradeLevel: "Middle",
        coordinates: { lat: 33.7231, lng: -116.2156 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Scorpions",
        bio: "Desert Ridge Academy offers a rigorous and dynamic learning environment for middle school students in grades 6-8, preparing them for high school and beyond.",
        phoneNumber: "(760) 393-5500",
        address: "79-767 Avenue 39, Indio, CA 92203",
        websiteUrl: "https://dra.dsusd.us/",
      },
      {
        id: "9",
        slug: "jefferson-middle-school",
        name: "Thomas Jefferson Middle School",
        gradeLevel: "Middle",
        coordinates: { lat: 33.7075, lng: -116.2145 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Jaguars",
        bio: "Thomas Jefferson Middle School focuses on academic achievement and personal growth for students in grades 6-8, fostering a community of respect and collaboration.",
        phoneNumber: "(760) 863-3660",
        address: "83-103 Avenue 48, Indio, CA 92201",
        websiteUrl: "https://jefferson.dsusd.us/",
      },
      {
        id: "10",
        slug: "paige-middle-school",
        name: "Paige Middle School",
        gradeLevel: "Middle",
        coordinates: { lat: 33.7334, lng: -116.3789 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Panthers",
        bio: "Paige Middle School provides students with a supportive and engaging environment, promoting academic excellence and social development for grades 6-8.",
        phoneNumber: "(760) 238-9720",
        address: "74-200 Country Club Drive, Palm Desert, CA 92260",
        websiteUrl: "https://paige.dsusd.us/",
      },
    ],
    HighSchool: [
      {
        id: "11",
        slug: "amistad-high-school",
        name: "Amistad High School",
        gradeLevel: "High School",
        coordinates: { lat: 33.7223, lng: -116.2167 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Eagles",
        bio: "Amistad High School provides alternative education programs designed to help students achieve their academic and personal goals.",
        phoneNumber: "(760) 775-3570",
        address: "45-768 Oasis Street, Indio, CA 92201",
        websiteUrl: "https://amistad.dsusd.us/",
      },
      {
        id: "12",
        slug: "palm-desert-high-school",
        name: "Palm Desert High School",
        gradeLevel: "High School",
        coordinates: { lat: 33.7296, lng: -116.3798 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Aztecs",
        bio: "Palm Desert High School offers a wide range of academic and extracurricular programs, fostering success for students in grades 9-12.",
        phoneNumber: "(760) 862-4300",
        address: "74-700 Aztec Road, Palm Desert, CA 92260",
        websiteUrl: "https://pdhs.dsusd.us/",
      },
      {
        id: "13",
        slug: "shadow-hills-high-school",
        name: "Shadow Hills High School",
        gradeLevel: "High School",
        coordinates: { lat: 33.7438, lng: -116.2307 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Knights",
        bio: "Shadow Hills High School is dedicated to academic excellence, innovation, and preparing students for success in college and careers.",
        phoneNumber: "(760) 393-5400",
        address: "39-225 Jefferson Street, Indio, CA 92203",
        websiteUrl: "https://shhs.dsusd.us/",
      },
      {
        id: "14",
        slug: "indio-high-school",
        name: "Indio High School",
        gradeLevel: "High School",
        coordinates: { lat: 33.719, lng: -116.2177 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Rajahs",
        bio: "Indio High School has a rich history of excellence, offering diverse academic and extracurricular opportunities to its students.",
        phoneNumber: "(760) 775-3550",
        address: "81-750 Avenue 46, Indio, CA 92201",
        websiteUrl: "https://ihs.dsusd.us/",
      },
      {
        id: "15",
        slug: "la-quinta-high-school",
        name: "La Quinta High School",
        gradeLevel: "High School",
        coordinates: { lat: 33.6777, lng: -116.3016 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Blackhawks",
        bio: "La Quinta High School is known for its strong academic programs, dedicated staff, and vibrant student community.",
        phoneNumber: "(760) 772-4150",
        address: "79-255 Westward Ho Drive, La Quinta, CA 92253",
        websiteUrl: "https://lqhs.dsusd.us/",
      },
    ],
  },
};

const palmSpringsUnifiedSchoolDistrict: SchoolDistrict = {
  name: "Palm Springs Unified School District",
  schools: {
    Elementary: [
      {
        id: "1",
        slug: "agua-caliente-elementary",
        name: "Agua Caliente Elementary",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.8314, lng: -116.5423 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Owls",
        bio: "Agua Caliente Elementary fosters academic excellence and creativity for students in grades K-5.",
        phoneNumber: "(760) 416-8235",
        address: "30800 San Luis Rey Dr, Cathedral City, CA 92234",
        websiteUrl: "http://aces.psusd.us",
      },
      {
        id: "2",
        slug: "bella-vista-elementary",
        name: "Bella Vista Elementary",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.9244, lng: -116.4821 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Tigers",
        bio: "Bella Vista Elementary provides a nurturing environment for students to achieve their academic potential.",
        phoneNumber: "(760) 251-7244",
        address: "65750 Avenida Jalisco, Desert Hot Springs, CA 92240",
        websiteUrl: "http://bves.psusd.us",
      },
      {
        id: "3",
        slug: "bubbling-wells-elementary",
        name: "Bubbling Wells Elementary",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.9434, lng: -116.4923 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Mustangs",
        bio: "Bubbling Wells Elementary is dedicated to academic achievement and lifelong learning for grades K-5.",
        phoneNumber: "(760) 251-7230",
        address: "67501 Camino Campanero, Desert Hot Springs, CA 92240",
        websiteUrl: "http://bwes.psusd.us",
      },
      {
        id: "4",
        slug: "cabot-yerxa-elementary",
        name: "Cabot Yerxa Elementary",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.9486, lng: -116.5034 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Explorers",
        bio: "Cabot Yerxa Elementary inspires students to reach their fullest potential through a supportive educational experience.",
        phoneNumber: "(760) 251-2223",
        address: "67067 Desert View Ave, Desert Hot Springs, CA 92240",
        websiteUrl: "http://cyes.psusd.us",
      },
      {
        id: "5",
        slug: "cahuilla-elementary",
        name: "Cahuilla Elementary",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.807, lng: -116.5137 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Roadrunners",
        bio: "Cahuilla Elementary serves students in grades K-5, emphasizing academic success and community values.",
        phoneNumber: "(760) 416-8161",
        address: "833 E Mesquite Ave, Palm Springs, CA 92264",
        websiteUrl: "http://caes.psusd.us",
      },
      {
        id: "6",
        slug: "cathedral-city-elementary",
        name: "Cathedral City Elementary",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.779, lng: -116.4653 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Cougars",
        bio: "Cathedral City Elementary focuses on fostering a love of learning and strong academic foundations for grades K-5.",
        phoneNumber: "(760) 770-8583",
        address: "69300 Converse Rd, Cathedral City, CA 92234",
        websiteUrl: "http://cces.psusd.us",
      },
    ],
    Middle: [
      {
        id: "1",
        slug: "desert-springs-middle",
        name: "Desert Springs Middle School",
        gradeLevel: "Middle",
        coordinates: { lat: 33.9553, lng: -116.5404 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Rattlers",
        bio: "Desert Springs Middle School provides a supportive and challenging environment for students in grades 6-8, preparing them for future success.",
        phoneNumber: "(760) 251-7200",
        address: "66755 Two Bunch Palms Trail, Desert Hot Springs, CA 92240",
        websiteUrl: "http://dsms.psusd.us",
      },
      {
        id: "2",
        slug: "james-workman-middle",
        name: "James Workman Middle School",
        gradeLevel: "Middle",
        coordinates: { lat: 33.8335, lng: -116.5396 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Wolves",
        bio: "James Workman Middle School offers diverse educational programs and extracurricular activities for students in grades 6-8.",
        phoneNumber: "(760) 770-8540",
        address: "69300 30th Avenue, Cathedral City, CA 92234",
        websiteUrl: "http://jwms.psusd.us",
      },
      {
        id: "3",
        slug: "nellie-coffman-middle",
        name: "Nellie N. Coffman Middle School",
        gradeLevel: "Middle",
        coordinates: { lat: 33.8011, lng: -116.455 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Cougars",
        bio: "Nellie N. Coffman Middle School fosters academic and personal growth for students in grades 6-8.",
        phoneNumber: "(760) 770-8617",
        address: "34603 Plumley Road, Cathedral City, CA 92234",
        websiteUrl: "http://ncms.psusd.us",
      },
      {
        id: "4",
        slug: "painted-hills-middle",
        name: "Painted Hills Middle School",
        gradeLevel: "Middle",
        coordinates: { lat: 33.9532, lng: -116.4762 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Panthers",
        bio: "Painted Hills Middle School emphasizes a well-rounded education and community values for students in grades 6-8.",
        phoneNumber: "(760) 251-1551",
        address: "9250 Sonora Drive, Desert Hot Springs, CA 92240",
        websiteUrl: "http://phms.psusd.us",
      },
      {
        id: "5",
        slug: "raymond-cree-middle",
        name: "Raymond Cree Middle School",
        gradeLevel: "Middle",
        coordinates: { lat: 33.8458, lng: -116.5375 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Eagles",
        bio: "Raymond Cree Middle School inspires academic excellence and lifelong learning for grades 6-8.",
        phoneNumber: "(760) 416-8283",
        address: "1011 E Vista Chino, Palm Springs, CA 92262",
        websiteUrl: "http://rcms.psusd.us",
      },
    ],
    HighSchool: [
      {
        id: "1",
        slug: "cathedral-city-high",
        name: "Cathedral City High School",
        gradeLevel: "High School",
        coordinates: { lat: 33.8017, lng: -116.4572 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Lions",
        bio: "Cathedral City High School offers diverse academic, arts, and athletic programs to prepare students for future success.",
        phoneNumber: "(760) 770-0100",
        address: "69250 Dinah Shore Drive, Cathedral City, CA 92234",
        websiteUrl: "http://catcityhigh.com/",
      },
      {
        id: "2",
        slug: "desert-hot-springs-high",
        name: "Desert Hot Springs High School",
        gradeLevel: "High School",
        coordinates: { lat: 33.9507, lng: -116.5003 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Golden Eagles",
        bio: "Desert Hot Springs High School emphasizes academic excellence, community involvement, and personal growth for grades 9-12.",
        phoneNumber: "(760) 288-7000",
        address: "65850 Pierson Blvd, Desert Hot Springs, CA 92240",
        websiteUrl: "http://dhshs.psusd.us",
      },
      {
        id: "3",
        slug: "palm-springs-high",
        name: "Palm Springs High School",
        gradeLevel: "High School",
        coordinates: { lat: 33.8303, lng: -116.5201 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Indians",
        bio: "Palm Springs High School boasts a strong academic program and a rich history of extracurricular achievement.",
        phoneNumber: "(760) 778-0400",
        address: "2401 E Baristo Road, Palm Springs, CA 92262",
        websiteUrl: "https://www.pshs.us/",
      },
      {
        id: "4",
        slug: "rancho-mirage-high",
        name: "Rancho Mirage High School",
        gradeLevel: "High School",
        coordinates: { lat: 33.8046, lng: -116.4225 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Rattlers",
        bio: "Rancho Mirage High School provides innovative educational programs and extracurricular activities for grades 9-12.",
        phoneNumber: "(760) 202-6455",
        address: "31001 Rattler Road, Rancho Mirage, CA 92270",
        websiteUrl: "https://www.rmhs.us/",
      },
    ],
  },
};

const coachellaValleyUnifiedSchoolDistrict: SchoolDistrict = {
  name: "Coachella Valley Unified School District",
  schools: {
    Elementary: [
      {
        id: "1",
        slug: "cesar-chavez-elementary",
        name: "Cesar Chavez Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.6824, lng: -116.1625 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Roadrunners",
        bio: "Cesar Chavez Elementary fosters a safe, supportive learning environment for grades K-6, encouraging academic growth and creativity.",
        phoneNumber: "(760) 398-6302",
        address: "83001 Ave 52, Coachella, CA 92236",
        websiteUrl: "https://cces.cvusd.us/",
      },
      {
        id: "2",
        slug: "coral-mountain-academy",
        name: "Coral Mountain Academy",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.6037, lng: -116.2107 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Tigers",
        bio: "Coral Mountain Academy provides a robust K-6 educational program emphasizing academic excellence and creativity.",
        phoneNumber: "(760) 398-6307",
        address: "51711 Frederick St, Coachella, CA 92236",
        websiteUrl: "https://cma.cvusd.us/",
      },
      {
        id: "3",
        slug: "john-kelley-elementary",
        name: "John Kelley Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.6188, lng: -116.1839 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Explorers",
        bio: "John Kelley Elementary encourages students in grades K-6 to explore and achieve their potential.",
        phoneNumber: "(760) 398-6308",
        address: "87200 Airport Blvd, Thermal, CA 92274",
        websiteUrl: "https://jkes.cvusd.us/",
      },
      {
        id: "4",
        slug: "las-palmitas-elementary",
        name: "Las Palmitas Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.6118, lng: -116.1841 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Lions",
        bio: "Las Palmitas Elementary provides a nurturing environment for academic and personal growth in grades K-6.",
        phoneNumber: "(760) 398-6310",
        address: "86350 Airport Blvd, Thermal, CA 92274",
        websiteUrl: "https://lp.cvusd.us/",
      },
      {
        id: "5",
        slug: "mecca-elementary",
        name: "Mecca Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.5764, lng: -116.0713 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Coyotes",
        bio: "Mecca Elementary School focuses on fostering creativity and lifelong learning for K-6 students.",
        phoneNumber: "(760) 396-3141",
        address: "65250 Coahuilla St, Mecca, CA 92254",
        websiteUrl: "https://mes.cvusd.us/",
      },
      {
        id: "6",
        slug: "mountain-vista-elementary",
        name: "Mountain Vista Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.6921, lng: -116.1593 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Hawks",
        bio: "Mountain Vista Elementary fosters a love for learning and excellence in education for students in grades K-6.",
        phoneNumber: "(760) 398-6303",
        address: "49730 Jackson St, Coachella, CA 92236",
        websiteUrl: "https://mves.cvusd.us/",
      },
      {
        id: "7",
        slug: "oasis-elementary",
        name: "Oasis Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.5243, lng: -116.0978 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Owls",
        bio: "Oasis Elementary School provides a safe and supportive learning environment for K-6 students.",
        phoneNumber: "(760) 397-2213",
        address: "88100 74th Ave, Thermal, CA 92274",
        websiteUrl: "https://oes.cvusd.us/",
      },
      {
        id: "8",
        slug: "palm-view-elementary",
        name: "Palm View Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.6838, lng: -116.1739 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Eagles",
        bio: "Palm View Elementary School offers a comprehensive K-6 curriculum focusing on academic and personal growth.",
        phoneNumber: "(760) 398-6309",
        address: "85901 Avenue 48, Coachella, CA 92236",
        websiteUrl: "https://pves.cvusd.us/",
      },
      {
        id: "9",
        slug: "peter-pendleton-elementary",
        name: "Peter Pendleton Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.6805, lng: -116.1826 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Panthers",
        bio: "Peter Pendleton Elementary focuses on fostering a collaborative and innovative educational environment for students in grades K-6.",
        phoneNumber: "(760) 398-6304",
        address: "84400 Calle Rojo, Coachella, CA 92236",
        websiteUrl: "https://ppes.cvusd.us/",
      },
      {
        id: "10",
        slug: "saul-martinez-elementary",
        name: "Saul Martinez Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.6781, lng: -116.1658 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Bobcats",
        bio: "Saul Martinez Elementary inspires students to achieve academic and personal excellence in grades K-6.",
        phoneNumber: "(760) 398-6311",
        address: "65705 Johnson St, Thermal, CA 92274",
        websiteUrl: "https://smes.cvusd.us/",
      },
      {
        id: "11",
        slug: "sea-view-elementary",
        name: "Sea View Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.5142, lng: -116.0997 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Sharks",
        bio: "Sea View Elementary provides a rigorous and engaging educational program for students in grades K-6.",
        phoneNumber: "(760) 394-4474",
        address: "86100 Avenue 66, Thermal, CA 92274",
        websiteUrl: "https://sves.cvusd.us/",
      },
      {
        id: "12",
        slug: "valle-del-sol-elementary",
        name: "Valle del Sol Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.6905, lng: -116.1548 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Lobos",
        bio: "Valle del Sol Elementary provides a nurturing educational experience for students in grades K-6.",
        phoneNumber: "(760) 398-6306",
        address: "51-435 Van Buren St, Coachella, CA 92236",
        websiteUrl: "https://vdses.cvusd.us/",
      },
      {
        id: "13",
        slug: "valley-view-elementary",
        name: "Valley View Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.7071, lng: -116.1915 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Eagles",
        bio: "Valley View Elementary provides a strong foundation for lifelong learning and personal growth for students in grades K-6.",
        phoneNumber: "(760) 398-6305",
        address: "85270 Valley Rd, Coachella, CA 92236",
        websiteUrl: "https://vves.cvusd.us/",
      },
      {
        id: "14",
        slug: "westside-elementary",
        name: "Westside Elementary School",
        gradeLevel: "Elementary",
        coordinates: { lat: 33.6783, lng: -116.1874 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Wolves",
        bio: "Westside Elementary inspires students in grades K-6 to achieve excellence in academics and character.",
        phoneNumber: "(760) 398-6312",
        address: "82225 Airport Blvd, Thermal, CA 92274",
        websiteUrl: "https://wse.cvusd.us/",
      },
    ],
    Middle: [
      {
        id: "1",
        slug: "bobby-duke-middle",
        name: "Bobby Duke Middle School",
        gradeLevel: "Middle",
        coordinates: { lat: 33.6787, lng: -116.1725 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Knights",
        bio: "Bobby Duke Middle School fosters academic success and personal growth for students in grades 7-8.",
        phoneNumber: "(760) 398-6303",
        address: "85-437 Cairo St, Coachella, CA 92236",
        websiteUrl: "https://bdms.cvusd.us/",
      },
      {
        id: "2",
        slug: "cahuilla-desert-academy",
        name: "Cahuilla Desert Academy",
        gradeLevel: "Middle",
        coordinates: { lat: 33.7081, lng: -116.2172 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Coyotes",
        bio: "Cahuilla Desert Academy provides a rigorous and innovative academic program for students in grades 7-8.",
        phoneNumber: "(760) 398-0097",
        address: "82489 Avenue 52, Coachella, CA 92236",
        websiteUrl: "https://cda.cvusd.us/",
      },
      {
        id: "3",
        slug: "toro-canyon-middle",
        name: "Toro Canyon Middle School",
        gradeLevel: "Middle",
        coordinates: { lat: 33.5615, lng: -116.0743 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Tigers",
        bio: "Toro Canyon Middle School focuses on academic achievement and personal growth for students in grades 7-8.",
        phoneNumber: "(760) 398-0351",
        address: "87225 Church St, Thermal, CA 92274",
        websiteUrl: "https://tcms.cvusd.us/",
      },
    ],
    HighSchool: [
      {
        id: "1",
        slug: "coachella-valley-high",
        name: "Coachella Valley High School",
        gradeLevel: "High School",
        coordinates: { lat: 33.6761, lng: -116.1587 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Arabs",
        bio: "Coachella Valley High School provides a comprehensive education and extracurricular programs to prepare students for college and careers.",
        phoneNumber: "(760) 399-5183",
        address: "83-800 Airport Blvd, Thermal, CA 92274",
        websiteUrl: "https://cvhs.cvusd.us/",
      },
      {
        id: "2",
        slug: "desert-mirage-high",
        name: "Desert Mirage High School",
        gradeLevel: "High School",
        coordinates: { lat: 33.6018, lng: -116.1604 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Rams",
        bio: "Desert Mirage High School offers rigorous academics, arts, and athletic programs to support student success.",
        phoneNumber: "(760) 397-2255",
        address: "86-150 Avenue 66, Thermal, CA 92274",
        websiteUrl: "https://dmhs.cvusd.us/",
      },
      {
        id: "3",
        slug: "la-familia-high",
        name: "La Familia High School",
        gradeLevel: "High School",
        coordinates: { lat: 33.6762, lng: -116.1575 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Warriors",
        bio: "La Familia High School provides an alternative educational experience to help students achieve their academic and personal goals.",
        phoneNumber: "(760) 399-5929",
        address: "83-800 Airport Blvd, Thermal, CA 92274",
        websiteUrl: "https://lfhs.cvusd.us/",
      },
      {
        id: "4",
        slug: "west-shores-high",
        name: "West Shores High School",
        gradeLevel: "High School",
        coordinates: { lat: 33.3614, lng: -116.0287 },
        photoUrl: "",
        logoUrl: "",
        teamName: "Wildcats",
        bio: "West Shores High School serves students in grades 9-12, providing a comprehensive education in a supportive environment.",
        phoneNumber: "(760) 394-4220",
        address: "2381 Shore Hawk Ave, Salton City, CA 92275",
        websiteUrl: "https://wshs.cvusd.us/",
      },
    ],
  },
};

export { desertSandsUnifiedSchoolDistrict, palmSpringsUnifiedSchoolDistrict, coachellaValleyUnifiedSchoolDistrict };
