-- ============================================================================
-- ChatRealty per-tenant data-plane schema — migration 0001_init
--
-- GENERATED by src/lib/reso/ddl.ts (buildFullSchemaDDL). Do NOT hand-edit:
-- src/lib/reso/migrations/0001_init.sql is asserted byte-identical to this
-- generator's output by src/lib/reso/__tests__/ddl.test.ts. Change the
-- catalog (data-dictionary.ts) or the generator, then regenerate.
--
-- Applied at tenant-provision time over the DIRECT (non-pooled) connection
-- (pgBouncer cannot run CREATE EXTENSION / session DDL). build_plan §6.2.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ----------------------------------------------------------------------------
-- Property (property)
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS property (
  listing_key text PRIMARY KEY,
  listing_id text,
  slug text NOT NULL,
  slug_address text,
  mls_source text NOT NULL,
  mls_id text NOT NULL,
  property_type text,
  property_sub_type text,
  standard_status text,
  list_price double precision,
  current_price double precision,
  original_list_price double precision,
  bedrooms_total integer,
  beds_total integer,
  bathrooms_total_integer integer,
  bathrooms_full integer,
  bathrooms_half integer,
  bathrooms_total_decimal double precision,
  living_area double precision,
  building_area_total double precision,
  year_built integer,
  lot_size_sqft double precision,
  lot_size_acres double precision,
  pool_yn boolean,
  spa_yn boolean,
  view_yn boolean,
  "view" text,
  garage_spaces integer,
  stories integer,
  senior_community_yn boolean,
  unparsed_address text,
  street_name text,
  street_number text,
  city text,
  subdivision_name text,
  state_or_province text,
  postal_code text,
  county_or_parish text,
  latitude double precision,
  longitude double precision,
  geom geometry(Point,4326),
  on_market_date timestamptz,
  days_on_market integer,
  cumulative_days_on_market integer,
  modification_timestamp timestamptz,
  price_change_timestamp timestamptz,
  primary_photo_url text,
  public_remarks text,
  list_agent_name text NOT NULL,
  list_agent_mls_id text,
  list_agent_preferred_phone text,
  list_office_name text NOT NULL,
  list_office_mls_id text,
  list_office_phone text,
  cma_stats jsonb,
  cashflow_stats jsonb,
  extras jsonb,
  raw jsonb
);

CREATE INDEX IF NOT EXISTS idx_property_listing_id ON property (listing_id);
CREATE INDEX IF NOT EXISTS idx_property_slug ON property (slug);
CREATE INDEX IF NOT EXISTS idx_property_slug_address ON property (slug_address);
CREATE INDEX IF NOT EXISTS idx_property_mls_source ON property (mls_source);
CREATE INDEX IF NOT EXISTS idx_property_mls_id ON property (mls_id);
CREATE INDEX IF NOT EXISTS idx_property_property_type ON property (property_type);
CREATE INDEX IF NOT EXISTS idx_property_standard_status ON property (standard_status);
CREATE INDEX IF NOT EXISTS idx_property_list_price ON property (list_price);
CREATE INDEX IF NOT EXISTS idx_property_bedrooms_total ON property (bedrooms_total);
CREATE INDEX IF NOT EXISTS idx_property_beds_total ON property (beds_total);
CREATE INDEX IF NOT EXISTS idx_property_bathrooms_total_integer ON property (bathrooms_total_integer);
CREATE INDEX IF NOT EXISTS idx_property_year_built ON property (year_built);
CREATE INDEX IF NOT EXISTS idx_property_pool_yn ON property (pool_yn);
CREATE INDEX IF NOT EXISTS idx_property_unparsed_address ON property (unparsed_address);
CREATE INDEX IF NOT EXISTS idx_property_city ON property (city);
CREATE INDEX IF NOT EXISTS idx_property_subdivision_name ON property (subdivision_name);
CREATE INDEX IF NOT EXISTS idx_property_postal_code ON property (postal_code);
CREATE INDEX IF NOT EXISTS idx_property_geom_gist ON property USING GIST (geom);
CREATE INDEX IF NOT EXISTS idx_property_on_market_date ON property (on_market_date);
CREATE INDEX IF NOT EXISTS idx_property_modification_timestamp ON property (modification_timestamp);
CREATE INDEX IF NOT EXISTS idx_property_price_change_timestamp ON property (price_change_timestamp);
CREATE INDEX IF NOT EXISTS idx_property_extras_gin ON property USING GIN (extras jsonb_path_ops);

-- ----------------------------------------------------------------------------
-- Property — ported compound indexes
-- ----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_property_mls_source_id ON property (mls_source, mls_id);
CREATE INDEX IF NOT EXISTS idx_property_city_status ON property (city, standard_status);
CREATE INDEX IF NOT EXISTS idx_property_subdivision_status ON property (subdivision_name, standard_status);
CREATE INDEX IF NOT EXISTS idx_property_type_status ON property (property_type, standard_status);
CREATE INDEX IF NOT EXISTS idx_property_city_type_price ON property (city, property_type, list_price);
CREATE INDEX IF NOT EXISTS idx_property_city_status_type_beds ON property (city, standard_status, property_type, beds_total);
CREATE INDEX IF NOT EXISTS idx_property_city_status_type_bedrooms ON property (city, standard_status, property_type, bedrooms_total);
CREATE INDEX IF NOT EXISTS idx_property_city_status_type_baths ON property (city, standard_status, property_type, bathrooms_total_integer);
CREATE INDEX IF NOT EXISTS idx_property_subdiv_status_type_beds ON property (subdivision_name, standard_status, property_type, beds_total);
CREATE INDEX IF NOT EXISTS idx_property_subdiv_status_type_bedrooms ON property (subdivision_name, standard_status, property_type, bedrooms_total);
CREATE INDEX IF NOT EXISTS idx_property_subdiv_status_type_baths ON property (subdivision_name, standard_status, property_type, bathrooms_total_integer);
CREATE INDEX IF NOT EXISTS idx_property_city_cashflow20 ON property (city, ((cashflow_stats #>> '{scenarios,down20,monthlyCashflow}')::numeric) DESC);
CREATE INDEX IF NOT EXISTS idx_property_zip_cashflow20 ON property (postal_code, ((cashflow_stats #>> '{scenarios,down20,monthlyCashflow}')::numeric) DESC);
CREATE INDEX IF NOT EXISTS idx_property_unparsed_address_trgm ON property USING GIN (unparsed_address gin_trgm_ops);

-- ----------------------------------------------------------------------------
-- Member (member)
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS member (
  member_key text PRIMARY KEY,
  member_mls_id text,
  member_full_name text,
  member_first_name text,
  member_last_name text,
  member_email text,
  member_preferred_phone text,
  member_type text,
  office_mls_id text,
  modification_timestamp timestamptz,
  extras jsonb
);

CREATE INDEX IF NOT EXISTS idx_member_member_mls_id ON member (member_mls_id);
CREATE INDEX IF NOT EXISTS idx_member_office_mls_id ON member (office_mls_id);
CREATE INDEX IF NOT EXISTS idx_member_modification_timestamp ON member (modification_timestamp);
CREATE INDEX IF NOT EXISTS idx_member_extras_gin ON member USING GIN (extras jsonb_path_ops);

-- ----------------------------------------------------------------------------
-- Office (office)
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS office (
  office_key text PRIMARY KEY,
  office_mls_id text,
  office_name text,
  office_phone text,
  office_email text,
  office_address1 text,
  office_city text,
  office_state_or_province text,
  office_postal_code text,
  modification_timestamp timestamptz,
  extras jsonb
);

CREATE INDEX IF NOT EXISTS idx_office_office_mls_id ON office (office_mls_id);
CREATE INDEX IF NOT EXISTS idx_office_modification_timestamp ON office (modification_timestamp);
CREATE INDEX IF NOT EXISTS idx_office_extras_gin ON office USING GIN (extras jsonb_path_ops);

-- ----------------------------------------------------------------------------
-- Media (media)
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS media (
  media_key text PRIMARY KEY,
  resource_record_key text,
  media_url text,
  media_type text,
  media_category text,
  media_order integer,
  caption text,
  image_width integer,
  image_height integer,
  modification_timestamp timestamptz,
  extras jsonb
);

CREATE INDEX IF NOT EXISTS idx_media_resource_record_key ON media (resource_record_key);
CREATE INDEX IF NOT EXISTS idx_media_modification_timestamp ON media (modification_timestamp);
CREATE INDEX IF NOT EXISTS idx_media_extras_gin ON media USING GIN (extras jsonb_path_ops);

-- ----------------------------------------------------------------------------
-- custom_field_registry
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS custom_field_registry (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  resource text NOT NULL,
  name text NOT NULL,
  field_type text NOT NULL,
  label text,
  searchable boolean NOT NULL DEFAULT false,
  enum_values jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT custom_field_registry_resource_name_key UNIQUE (resource, name)
);

CREATE INDEX IF NOT EXISTS idx_custom_field_registry_resource ON custom_field_registry (resource);

-- ----------------------------------------------------------------------------
-- schema_migrations
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS schema_migrations (
  version text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);
