#!/usr/bin/env python3
"""
Generate County Boundaries for Map Visualization
================================================

Reads California county GeoJSON and outputs TypeScript file with individual
county polygon boundaries for map rendering.

Output: src/data/county-boundaries.ts
"""

import json
from shapely.geometry import shape, mapping
from shapely.ops import unary_union

print("Generating California county boundaries...")
print()

# Load county GeoJSON
print("Loading county GeoJSON...")
with open('ca_counties.json', 'r') as f:
    geojson = json.load(f)

print(f"   Loaded {len(geojson['features'])} counties")
print()

# Process each county
county_boundaries = {}

for feature in geojson['features']:
    county_name = feature['properties']['name']

    # Create geometry from GeoJSON
    geom = shape(feature['geometry'])

    # Fix invalid geometries
    if not geom.is_valid:
        print(f"   Fixing invalid geometry for {county_name}...")
        geom = geom.buffer(0)

    # Simplify to reduce coordinate count (0.01 degree tolerance ~1km)
    geom = geom.simplify(0.01, preserve_topology=True)

    # Convert to GeoJSON coordinates format
    geojson_geom = mapping(geom)
    coords = geojson_geom['coordinates']
    geom_type = geojson_geom['type']

    # Store boundary
    county_boundaries[county_name] = {
        'type': geom_type,
        'coordinates': coords
    }

    # Count coordinates
    def count_coords(c):
        if isinstance(c[0], (int, float)):
            return 1
        return sum(count_coords(x) for x in c)

    coord_count = count_coords(coords)
    print(f"   {county_name}: {geom_type}, ~{coord_count} coordinates")

print()
print(f"Processed {len(county_boundaries)} counties")
print()

# Generate TypeScript output
print("Generating TypeScript output...")

ts_output = """// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate-county-boundaries.py
// Source: California county GeoJSON from Code for America

export interface CountyBoundary {
  type: 'Polygon' | 'MultiPolygon';
  coordinates: number[][][] | number[][][][];
}

export const COUNTY_BOUNDARIES: Record<string, CountyBoundary> = {
"""

for county_name, boundary in sorted(county_boundaries.items()):
    boundary_json = json.dumps(boundary, separators=(",", ":"))
    ts_output += f'  "{county_name}": {boundary_json},\n'

ts_output += "};\n"

# Write to file
output_path = 'src/data/county-boundaries.ts'
with open(output_path, 'w') as f:
    f.write(ts_output)

print(f"SUCCESS: County boundaries saved to {output_path}")
print()

# Summary
print("Summary:")
for county_name, boundary in sorted(county_boundaries.items()):
    coord_count = sum(1 for _ in str(boundary['coordinates']).split('['))
    print(f"   {county_name}: {boundary['type']}, ~{coord_count} coordinates")
